### ISSUE TITLE
Javadoc building full of warnings

### ISSUE THREAD

**Issue by jteheran** [CROSSINGTUD/bc-hybrid-certificates#3]
When building the API documentation I got a bunch of warnings.

`> Task :javadoc
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/cert/HybridSignatureCertificateBuilder.java:109: warning: no @throws for java.io.IOException
    public X509CertificateHolder buildHybrid(ContentSigner primary, ContentSigner secondary) throws IOException {
`

`                             
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/cert/HybridCertUtils.java:19: warning: no @throws for java.io.IOException
    public static byte[] extractBaseCertSearch(X509Certificate cert) throws IOException, CertificateEncodingException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/cert/HybridCertUtils.java:19: warning: no @throws for java.security.cert.CertificateEncodingException
    public static byte[] extractBaseCertSearch(X509Certificate cert) throws IOException, CertificateEncodingException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/cert/HybridKeyCertificateBuilder.java:109: warning: no @throws for java.io.IOException
    public X509CertificateHolder buildHybrid(ContentSigner primary) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/pkcs/HybridCSRBuilder.java:70: warning: no @throws for java.io.IOException
    public void addExtension(ASN1ObjectIdentifier oid, boolean isCritical, ASN1Encodable value) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/pkcs/HybridCSRBuilder.java:110: warning: no @throws for java.io.IOException
    public PKCS10CertificationRequest buildHybrid(ContentSigner primary, ContentSigner secondary) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/pkcs/HybridCSRUtils.java:17: warning: no @throws for java.io.IOException
    public static byte[] extractBaseCSRSearch(PKCS10CertificationRequest csr) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/asn1/x509/HybridKey.java:28: warning: no @throws for java.io.IOException
    public HybridKey(AsymmetricKeyParameter key) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/asn1/x509/HybridKey.java:73: warning: no @throws for java.io.IOException
    public static HybridKey fromCert(X509Certificate cert) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/asn1/x509/HybridKey.java:87: warning: no @throws for java.io.IOException
    public static HybridKey fromCSR(PKCS10CertificationRequest csr) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/asn1/x509/HybridSignature.java:64: warning: no @throws for java.io.IOException
    public static HybridSignature fromCert(X509Certificate cert) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/asn1/x509/HybridSignature.java:80: warning: no @throws for java.io.IOException
    public static HybridSignature fromCSR(PKCS10CertificationRequest csr) throws IOException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/x509/VerifyHelper.java:18: warning: no @throws for java.security.NoSuchAlgorithmException
    public static Signature createSignature(AlgorithmIdentifier algId) throws NoSuchAlgorithmException, SignatureException, InvalidKeyException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/x509/VerifyHelper.java:18: warning: no @throws for java.security.SignatureException
    public static Signature createSignature(AlgorithmIdentifier algId) throws NoSuchAlgorithmException, SignatureException, InvalidKeyException {
`

`  
/../../../bc-hybrid-certificates-master/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/x509/VerifyHelper.java:18: warning: no @throws for java.security.InvalidKeyException
    public static Signature createSignature(AlgorithmIdentifier algId) throws NoSuchAlgorithmException, SignatureException, InvalidKeyException {
`

`  
15 warnings`

**Comment by wirthjohannes** [comment]
I just added the missing @throws annotations.
